//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustManager.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AppCollections : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppCollections defaultInstance = ((AppCollections)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppCollections())));
        
        public static AppCollections Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bradley.enabled</string>\r\n  <string>ai.think</string>\r\n  <string>ai.move</" +
            "string>\r\n  <string>ai.sensetime</string>\r\n  <string>ai.frametime</string>\r\n  <st" +
            "ring>ai.tickrate</string>\r\n  <string>antihack.enabled</string>\r\n  <string>antiha" +
            "ck.admincheat</string>\r\n  <string>antihack.objectplacement</string>\r\n  <string>a" +
            "ntihack.modelstate</string>\r\n  <string>antihack.userlevel</string>\r\n  <string>an" +
            "tihack.enforcementlevel</string>\r\n  <string>antihack.maxdesync</string>\r\n  <stri" +
            "ng>antihack.relaxationrate</string>\r\n  <string>antihack.relaxationpause</string>" +
            "\r\n  <string>antihack.maxviolation</string>\r\n  <string>antihack.noclip_protection" +
            "</string>\r\n  <string>antihack.noclip_reject</string>\r\n  <string>antihack.noclip_" +
            "penalty</string>\r\n  <string>antihack.noclip_stepsize</string>\r\n  <string>antihac" +
            "k.noclip_maxsteps</string>\r\n  <string>antihack.speedhack_protection</string>\r\n  " +
            "<string>antihack.speedhack_reject</string>\r\n  <string>antihack.speedhack_penalty" +
            "</string>\r\n  <string>antihack.speedhack_forgiveness</string>\r\n  <string>antihack" +
            ".speedhack_deltatime</string>\r\n  <string>antihack.speedhack_tickets</string>\r\n  " +
            "<string>antihack.speedhack_history</string>\r\n  <string>antihack.flyhack_protecti" +
            "on</string>\r\n  <string>antihack.flyhack_reject</string>\r\n  <string>antihack.flyh" +
            "ack_penalty</string>\r\n  <string>antihack.flyhack_forgiveness</string>\r\n  <string" +
            ">antihack.projectile_protection</string>\r\n  <string>antihack.projectile_penalty<" +
            "/string>\r\n  <string>antihack.projectile_forgiveness</string>\r\n  <string>antihack" +
            ".projectile_padding</string>\r\n  <string>antihack.projectile_serverframes</string" +
            ">\r\n  <string>antihack.projectile_clientframes</string>\r\n  <string>antihack.proje" +
            "ctile_tickets</string>\r\n  <string>antihack.melee_protection</string>\r\n  <string>" +
            "antihack.melee_penalty</string>\r\n  <string>antihack.melee_forgiveness</string>\r\n" +
            "  <string>antihack.melee_padding</string>\r\n  <string>antihack.melee_serverframes" +
            "</string>\r\n  <string>antihack.melee_clientframes</string>\r\n  <string>antihack.me" +
            "lee_tickets</string>\r\n  <string>antihack.eye_protection</string>\r\n  <string>anti" +
            "hack.eye_penalty</string>\r\n  <string>antihack.debuglevel</string>\r\n  <string>bat" +
            "ching.colliders</string>\r\n  <string>batching.collider_vertices</string>\r\n  <stri" +
            "ng>batching.collider_submeshes</string>\r\n  <string>batching.verbose</string>\r\n  " +
            "<string>chat.enabled</string>\r\n  <string>chat.serverlog</string>\r\n  <string>cons" +
            "truct.frameminutes</string>\r\n  <string>craft.instant</string>\r\n  <string>debug.c" +
            "hecktriggers</string>\r\n  <string>decay.tick</string>\r\n  <string>decay.scale</str" +
            "ing>\r\n  <string>decay.debug</string>\r\n  <string>env.time</string>\r\n  <string>env" +
            ".day</string>\r\n  <string>env.month</string>\r\n  <string>env.year</string>\r\n  <str" +
            "ing>fps.limit</string>\r\n  <string>gc.interval</string>\r\n  <string>heli.lifetimem" +
            "inutes</string>\r\n  <string>heli.guns</string>\r\n  <string>heli.bulletdamagescale<" +
            "/string>\r\n  <string>heli.bulletaccuracy</string>\r\n  <string>net.visdebug</string" +
            ">\r\n  <string>physics.droppedmode</string>\r\n  <string>physics.sendeffects</string" +
            ">\r\n  <string>physics.bouncethreshold</string>\r\n  <string>physics.sleepthreshold<" +
            "/string>\r\n  <string>physics.solveriterationcount</string>\r\n  <string>physics.ste" +
            "ps</string>\r\n  <string>pool.skins</string>\r\n  <string>sentry.targetall</string>\r" +
            "\n  <string>sentry.hostileduration</string>\r\n  <string>server.ip</string>\r\n  <str" +
            "ing>server.port</string>\r\n  <string>server.maxplayers</string>\r\n  <string>server" +
            ".hostname</string>\r\n  <string>server.identity</string>\r\n  <string>server.level</" +
            "string>\r\n  <string>server.seed</string>\r\n  <string>server.salt</string>\r\n  <stri" +
            "ng>server.worldsize</string>\r\n  <string>server.saveinterval</string>\r\n  <string>" +
            "server.secure</string>\r\n  <string>server.tickrate</string>\r\n  <string>server.ent" +
            "ityrate</string>\r\n  <string>server.cycletime</string>\r\n  <string>server.official" +
            "</string>\r\n  <string>server.globalchat</string>\r\n  <string>server.stability</str" +
            "ing>\r\n  <string>server.radiation</string>\r\n  <string>server.itemdespawn</string>" +
            "\r\n  <string>server.pve</string>\r\n  <string>server.description</string>\r\n  <strin" +
            "g>server.headerimage</string>\r\n  <string>server.logoimage</string>\r\n  <string>se" +
            "rver.url</string>\r\n  <string>server.branch</string>\r\n  <string>server.eac</strin" +
            "g>\r\n  <string>server.queriespersecond</string>\r\n  <string>server.ipqueriespermin" +
            "</string>\r\n  <string>server.meleedamage</string>\r\n  <string>server.arrowdamage</" +
            "string>\r\n  <string>server.bulletdamage</string>\r\n  <string>server.bleedingdamage" +
            "</string>\r\n  <string>server.meleearmor</string>\r\n  <string>server.arrowarmor</st" +
            "ring>\r\n  <string>server.bulletarmor</string>\r\n  <string>server.bleedingarmor</st" +
            "ring>\r\n  <string>server.updatebatch</string>\r\n  <string>server.planttick</string" +
            ">\r\n  <string>server.planttickscale</string>\r\n  <string>server.respawnresetrange<" +
            "/string>\r\n  <string>server.maxunack</string>\r\n  <string>server.maxflood</string>" +
            "\r\n  <string>server.netcache</string>\r\n  <string>server.netcachesize</string>\r\n  " +
            "<string>server.savecachesize</string>\r\n  <string>server.combatlogsize</string>\r\n" +
            "  <string>server.idlekick</string>\r\n  <string>server.idlekickmode</string>\r\n  <s" +
            "tring>server.idlekickadmins</string>\r\n  <string>server.maxreceivetime</string>\r\n" +
            "  <string>server.compression</string>\r\n  <string>server.netlog</string>\r\n  <stri" +
            "ng>spawn.min_rate</string>\r\n  <string>spawn.max_rate</string>\r\n  <string>spawn.m" +
            "in_density</string>\r\n  <string>spawn.max_density</string>\r\n  <string>stability.v" +
            "erbose</string>\r\n  <string>stability.strikes</string>\r\n  <string>stability.colla" +
            "pse</string>\r\n  <string>stability.accuracy</string>\r\n  <string>time.fixeddelta</" +
            "string>\r\n  <string>time.maxdelta</string>\r\n  <string>vis.damage</string>\r\n  <str" +
            "ing>vis.attack</string>\r\n  <string>vis.protection</string>\r\n  <string>vis.weaksp" +
            "ots</string>\r\n  <string>vis.triggers</string>\r\n  <string>vis.hitboxes</string>\r\n" +
            "  <string>vis.lineofsight</string>\r\n  <string>xmas.enabled</string>\r\n  <string>x" +
            "mas.spawnrange</string>\r\n  <string>xmas.giftsperplayer</string>\r\n  <string>rcon." +
            "print</string>\r\n  <string>find</string>\r\n  <string>status</string>\r\n  <string>st" +
            "ats</string>\r\n  <string>kick</string>\r\n  <string>kickall</string>\r\n  <string>ban" +
            "</string>\r\n  <string>moderatorid</string>\r\n  <string>ownerid</string>\r\n  <string" +
            ">removemoderator</string>\r\n  <string>removeowner</string>\r\n  <string>banid</stri" +
            "ng>\r\n  <string>unban</string>\r\n  <string>players</string>\r\n  <string>say</string" +
            ">\r\n  <string>users</string>\r\n  <string>banlist</string>\r\n  <string>banlistex</st" +
            "ring>\r\n  <string>listid</string>\r\n  <string>mutevoice</string>\r\n  <string>unmute" +
            "voice</string>\r\n  <string>mutechat</string>\r\n  <string>unmutechat</string>\r\n  <s" +
            "tring>playerlist</string>\r\n  <string>bans</string>\r\n  <string>serverinfo</string" +
            ">\r\n  <string>batching.refresh_colliders</string>\r\n  <string>batching.status</str" +
            "ing>\r\n  <string>chat.tail</string>\r\n  <string>chat.search</string>\r\n  <string>co" +
            "nsole.tail</string>\r\n  <string>console.search</string>\r\n  <string>data.export</s" +
            "tring>\r\n  <string>flushgroup</string>\r\n  <string>breakheld</string>\r\n  <string>b" +
            "reakitem</string>\r\n  <string>hurt</string>\r\n  <string>entity.debug_toggle</strin" +
            "g>\r\n  <string>entity.nudge</string>\r\n  <string>entity.create</string>\r\n  <string" +
            ">env.addtime</string>\r\n  <string>gc.collect</string>\r\n  <string>gc.unload</strin" +
            "g>\r\n  <string>global.restart</string>\r\n  <string>global.quit</string>\r\n  <string" +
            ">global.report</string>\r\n  <string>global.objects</string>\r\n  <string>global.tex" +
            "tures</string>\r\n  <string>global.colliders</string>\r\n  <string>global.error</str" +
            "ing>\r\n  <string>global.queue</string>\r\n  <string>global.sleep</string>\r\n  <strin" +
            "g>global.injure</string>\r\n  <string>global.spectate</string>\r\n  <string>global.t" +
            "eleport</string>\r\n  <string>global.teleport2me</string>\r\n  <string>global.telepo" +
            "rtany</string>\r\n  <string>global.teleportpos</string>\r\n  <string>global.cleanup<" +
            "/string>\r\n  <string>global.version</string>\r\n  <string>global.sysinfo</string>\r\n" +
            "  <string>global.breakitem</string>\r\n  <string>heli.drop</string>\r\n  <string>hel" +
            "i.calltome</string>\r\n  <string>heli.call</string>\r\n  <string>heli.strafe</string" +
            ">\r\n  <string>hierarchy.ls</string>\r\n  <string>hierarchy.cd</string>\r\n  <string>h" +
            "ierarchy.del</string>\r\n  <string>inventory.give</string>\r\n  <string>inventory.gi" +
            "veall</string>\r\n  <string>inventory.giveto</string>\r\n  <string>inventory.giveid<" +
            "/string>\r\n  <string>inventory.givearm</string>\r\n  <string>pool.print_memory</str" +
            "ing>\r\n  <string>pool.print_prefabs</string>\r\n  <string>pool.print_assets</string" +
            ">\r\n  <string>pool.clear_memory</string>\r\n  <string>pool.clear_prefabs</string>\r\n" +
            "  <string>pool.clear_assets</string>\r\n  <string>server.stop</string>\r\n  <string>" +
            "server.backup</string>\r\n  <string>server.writecfg</string>\r\n  <string>server.fps" +
            "</string>\r\n  <string>server.save</string>\r\n  <string>server.readcfg</string>\r\n  " +
            "<string>spawn.fill_populations</string>\r\n  <string>spawn.fill_groups</string>\r\n " +
            " <string>spawn.report</string>\r\n  <string>weather.clouds</string>\r\n  <string>wea" +
            "ther.fog</string>\r\n  <string>weather.wind</string>\r\n  <string>weather.rain</stri" +
            "ng>\r\n  <string>xmas.refill</string>\r\n  <string>global.dump</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection ConsoleCommandsCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConsoleCommandsCollection"]));
            }
            set {
                this["ConsoleCommandsCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ConsoleMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConsoleMessages"]));
            }
            set {
                this["ConsoleMessages"] = value;
            }
        }
    }
}
