//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustManager.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AppInstallerData : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppInstallerData defaultInstance = ((AppInstallerData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppInstallerData())));
        
        public static AppInstallerData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TempServerIndex {
            get {
                return ((int)(this["TempServerIndex"]));
            }
            set {
                this["TempServerIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempServerRootPath {
            get {
                return ((string)(this["TempServerRootPath"]));
            }
            set {
                this["TempServerRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempCurrentServer {
            get {
                return ((string)(this["TempCurrentServer"]));
            }
            set {
                this["TempCurrentServer"] = value;
            }
        }
    }
}
