//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustManager.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AppUserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppUserSettings defaultInstance = ((AppUserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppUserSettings())));
        
        public static AppUserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BackupCleanEnabled {
            get {
                return ((bool)(this["BackupCleanEnabled"]));
            }
            set {
                this["BackupCleanEnabled"] = value;
            }
        }
    }
}
