//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustManager.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class DataLog : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataLog defaultInstance = ((DataLog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataLog())));
        
        public static DataLog Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RestartTimeLeft {
            get {
                return ((int)(this["RestartTimeLeft"]));
            }
            set {
                this["RestartTimeLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RestartTimeProcessed {
            get {
                return ((int)(this["RestartTimeProcessed"]));
            }
            set {
                this["RestartTimeProcessed"] = value;
            }
        }
    }
}
