//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustManager.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ServerDataLog : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServerDataLog defaultInstance = ((ServerDataLog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServerDataLog())));
        
        public static ServerDataLog Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerStatus {
            get {
                return ((string)(this["ServerStatus"]));
            }
            set {
                this["ServerStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ServerStalledPoints {
            get {
                return ((int)(this["ServerStalledPoints"]));
            }
            set {
                this["ServerStalledPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ServerStalledMaxPoints {
            get {
                return ((int)(this["ServerStalledMaxPoints"]));
            }
            set {
                this["ServerStalledMaxPoints"] = value;
            }
        }
    }
}
